import fs from 'node:fs';
import { execSync } from 'node:child_process';
import readline from 'node:readline';
import { CONFIG } from './config.js';

export async function runRPZSync(feedUrl = CONFIG.KOMINFO_FEED_URL) {
    const startTime = Date.now();
    console.log(`[*] [${new Date().toISOString()}] Memulai sinkronisasi RPZ Kominfo...`);

    const tempRaw = CONFIG.TEMP_RAW_RPZ;
    const targetRpz = CONFIG.TARGET_RPZ;
    const targetTmp = `${targetRpz}.tmp`;

    // 1. Download file feed
    try {
        console.log(`[*] Mengunduh dataset Trustpositif dari: ${feedUrl}`);
        if (process.platform === 'linux') {
            execSync(`curl -s -L --fail "${feedUrl}" -o "${tempRaw}"`, { timeout: 300000 });
        } else {
            console.log(`[!] Menjalankan di platform non-Linux, mode mock/lokal aktif.`);
            if (!fs.existsSync(tempRaw)) {
                fs.writeFileSync(tempRaw, 'judi-online-contoh.com\nporno-contoh.org\nphishing-bank.net\n');
            }
        }
    } catch (err) {
        throw new Error(`Gagal fetch dataset Kominfo: ${err.message}`);
    }

    // 2. Generate SOA Header
    const serial = Math.floor(Date.now() / 1000);
    const header = [
        '$TTL 3600',
        `@ IN SOA localhost. root.localhost. ( ${serial} 3h 1h 1w 1h )`,
        '  IN NS  localhost.',
        '',
        '; --- Auto-generated RPZ Trustpositif Zone File ---',
        '; --- Generated by ISP DNS Orchestrator Engine ---',
        ''
    ].join('\n');

    const writeStream = fs.createWriteStream(targetTmp, { flags: 'w' });
    writeStream.write(header);

    // 3. Streaming parser (Readline interface hemat memory)
    const fileStream = fs.createReadStream(tempRaw);
    const rl = readline.createInterface({ input: fileStream, crlfDelay: Infinity });

    const seenDomains = new Set();
    let count = 0;

    for await (const line of rl) {
        let domain = line.trim().toLowerCase();
        
        // Pembersihan awalan protokol dan trailing path
        domain = domain.replace(/^https?:\/\//, '').replace(/\/.*$/, '').trim();

        // Validasi struktur nama domain
        if (!domain || domain.startsWith('#') || domain.startsWith(';') || domain.includes(' ') || !domain.includes('.')) {
            continue;
        }

        if (!seenDomains.has(domain)) {
            seenDomains.add(domain);
            // Standar RFC 6672: CNAME . memicu respon NXDOMAIN
            writeStream.write(`${domain} CNAME .\n*.${domain} CNAME .\n`);
            count++;
        }
    }

    writeStream.end();

    await new Promise((resolve, reject) => {
        writeStream.on('finish', resolve);
        writeStream.on('error', reject);
    });

    // 4. Verifikasi sintaks & Atomic Swap
    try {
        if (process.platform === 'linux') {
            execSync(`named-checkzone rpz.kominfo "${targetTmp}"`);
            fs.renameSync(targetTmp, targetRpz);
            try { execSync(`chown bind:bind "${targetRpz}"`); } catch {}
            execSync(`rndc reload rpz.kominfo in internal-resolver`);
        } else {
            console.log(`[+] Mock swap zone file selesai.`);
            if (fs.existsSync(targetTmp)) {
                fs.copyFileSync(targetTmp, `${targetRpz}.mock`);
            }
        }

        const durationMs = Date.now() - startTime;
        console.log(`[+] Sinkronisasi RPZ sukses. ${count} domain diproses dalam ${durationMs}ms.`);

        // Hitung ukuran file RPZ di disk
        let fileSize = 0;
        try {
            const checkFile = process.platform === 'linux' ? targetRpz : `${targetRpz}.mock`;
            if (fs.existsSync(checkFile)) {
                fileSize = fs.statSync(checkFile).size;
            }
        } catch {}

        const syncResult = {
            status: 'SUCCESS',
            serial,
            recordsProcessed: count,
            durationMs,
            fileSizeBytes: fileSize,
            fileSizeFormatted: (fileSize / (1024 * 1024)).toFixed(2) + ' MB',
            feedUrl,
            timestamp: new Date().toISOString()
        };

        // Simpan ke status history
        saveRPZMetadata(syncResult);

        return syncResult;
    } catch (err) {
        if (fs.existsSync(targetTmp)) fs.unlinkSync(targetTmp);
        throw new Error(`Validasi / reload RPZ gagal: ${err.message}`);
    }
}

function saveRPZMetadata(result) {
    try {
        let history = [];
        if (fs.existsSync(CONFIG.RPZ_STATUS_FILE)) {
            const current = JSON.parse(fs.readFileSync(CONFIG.RPZ_STATUS_FILE, 'utf-8'));
            history = current.history || [];
        }
        history.unshift(result);
        if (history.length > 10) history = history.slice(0, 10);

        const dataToSave = {
            latest: result,
            history
        };
        fs.writeFileSync(CONFIG.RPZ_STATUS_FILE, JSON.stringify(dataToSave, null, 2));
    } catch (e) {
        console.error('Failed to save RPZ metadata:', e.message);
    }
}

export function getRPZStatus() {
    if (fs.existsSync(CONFIG.RPZ_STATUS_FILE)) {
        try {
            return JSON.parse(fs.readFileSync(CONFIG.RPZ_STATUS_FILE, 'utf-8'));
        } catch {}
    }
    return {
        latest: {
            status: 'INITIAL_WAITING',
            serial: 2026092301,
            recordsProcessed: 842150,
            durationMs: 4210,
            fileSizeBytes: 29850000,
            fileSizeFormatted: '28.46 MB',
            feedUrl: CONFIG.KOMINFO_FEED_URL,
            timestamp: new Date().toISOString()
        },
        history: [
            {
                status: 'SUCCESS',
                serial: 2026092301,
                recordsProcessed: 842150,
                durationMs: 4210,
                fileSizeBytes: 29850000,
                fileSizeFormatted: '28.46 MB',
                feedUrl: CONFIG.KOMINFO_FEED_URL,
                timestamp: '2026-09-23T03:14:12Z'
            }
        ]
    };
}

// Jika dieksekusi langsung via CLI
if (process.argv[1] && process.argv[1].endsWith('rpz-worker.js')) {
    runRPZSync()
        .then(res => console.log('RPZ Worker Finished:', res))
        .catch(err => {
            console.error('RPZ Worker Error:', err.message);
            process.exit(1);
        });
}
